name: Reproduce DrMemory Issue #886

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Dr. Memory
      run: |
        curl -LO https://github.com/DynamoRIO/drmemory/releases/download/release_2.6.0/DrMemory-Windows-2.6.0.zip 
        tar -xvzf DrMemory-Windows-2.6.0.zip
        cd drmemory
        dir
        
        
    - name: Compile free.c test
      run: |
        # Replace with the actual source code of free.c if not in the repo
        gcc -o free.exe tests/free.c

    - name: Run Dr. Memory with malloc/free test
      run: |
        .\DrMemory-Windows-2.6.0\bin\drmemory.exe -pause_at_error -light -dr_ops "-msgbox_mask 0x1" -- .\free.exe
