name: Reproduce Dr. Memory Flaky Race Condition Issue #1557

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib 
        # libunwind8 libc6-dev g++ gcc libunwind-dev
        # wget https://github.com/DynamoRIO/drmemory/releases/download/release_2.6.0/DrMemory-Linux-2.6.0.tar.gz
        # tar -xzf DrMemory-Linux-2.6.0.tar.gz
        # export PATH=$PATH:$PWD/DrMemory-Linux-2.6.0/bin


    # - name: Run Dr. Memory Multiple Times
    #   run: |
    #     sudo sysctl -w kernel.randomize_va_space=0
    #     export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libunwind.so.8:$LD_LIBRARY_PATH
    #     for i in {1..10}; do
    #       echo "===== Run $i ====="
    #       ./DrMemory-Linux-2.6.0/bin/drmemory -- ./drmemory-false-positive | grep -A 1 Error
    #     done
    - name: Install Dr. Memory
      if: runner.os == 'Linux'
      run: | 
        sudo apt-get update
        sudo apt-get install -y libunwind8
        wget -P /tmp/ https://github.com/DynamoRIO/drmemory/releases/download/release_2.6.0/DrMemory-Linux-2.6.0.tar.gz && tar -xzf /tmp/DrMemory-Linux-2.6.0.tar.gz -C /tmp/

           
    # - name: Disable Address Space Randomization
    #   if: runner.os == 'Linux'
    #   run: sudo sysctl -w kernel.randomize_va_space=0
      
    # - name: Disable swapping 
    #   if: runner.os == 'Linux' 
    #   run: sudo swapoff -a
        
    - name: Run Dr. Memory
      run: |
        #!/bin/bash
        # set +e 
        gcc tests/free.c
        ls -l 
        for((i=0;i<100;i++)); do 
          echo "This is Run: $i"
          /tmp/DrMemory-Linux-2.6.0/bin64/drmemory -pause_at_error -light -dr_ops "-msgbox_mask 0x1" -- ./a.out
        done
